
spring:
  datasource:
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shiro
      initial-size: 5

  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.by.model
server:
  port: 8083


# 配置pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count
